name: ci

on:
    workflow_dispatch:
    push:
        tags:
            - v[0-9]+\.[0-9]+\.[0-9]+

env:
    REGEX: ^v([0-9]+)\.([0-9]+)\.([0-9]+)$

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - id: regex-match
              uses: actions-ecosystem/action-regex-match@v2
              with:
                  text: ${{ github.ref_name }}
                  regex: ${{ env.REGEX }}

            - id: string
              uses: ASzc/change-string-case-action@v6
              with:
                  string: ${{ github.repository }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ghcr.io/${{ steps.string.outputs.lowercase }}:latest
                      ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.regex-match.outputs.group1 }}
                      ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.regex-match.outputs.group1 }}.${{ steps.regex-match.outputs.group2 }}
                      ghcr.io/${{ steps.string.outputs.lowercase }}:${{ steps.regex-match.outputs.group1 }}.${{ steps.regex-match.outputs.group2 }}.${{ steps.regex-match.outputs.group3 }}
